spring:
  application:
    name: consumer
  cloud:
    stream:
      function:
        definition: processRiderLocation
      bindings:
        processRiderLocation-in-0:
          destination: topic-prueba
    kafka:
      binder:
        brokers: localhost:9092

server:
  port: 8081